name: Generate Sponsors README
on:
  workflow_dispatch:
  push:
    branches:
      - sponsors
  schedule:
    - cron: 30 15 * * 0-6
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Generate Sponsors ğŸ’–
        uses: JamesIves/github-sponsors-readme-action@v1
        with:
          token: ${{ secrets.PAT }}
          file: 'README.md'
          organization: true
          template: '<a href="{{ websiteUrl }}"><img src="{{ avatarUrl }}" width="65px" alt="User avatar: {{ name }}" /></a>'

      - name: Setup Git ğŸ› ï¸
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create branch and commit changes ğŸ”€
        run: |
          BRANCH="update-sponsors-$(date +%Y%m%d%H%M%S)"
          git checkout -b $BRANCH
          git add README.md
          git commit -m "chore: update sponsors list"
          git push origin $BRANCH
          echo "BRANCH_NAME=$BRANCH" >> $GITHUB_ENV

      - name: Create Pull Request ğŸ“¬
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Update Sponsors List ğŸ’–'
          body: 'This PR updates the README with the latest list of sponsors.'
          base: sponsors
          head: ${{ env.BRANCH_NAME }}
